library mylibrary.globals;
import 'package:kan_market/Models/item.dart';
import 'package:kan_market/Models/shop.dart';
String username='';
String firstname='';
String lastname='';
int userid;
List<Item> i=[];
List<Shop> sh=[];